name: yushituoqie

on:
  workflow_dispatch:
  schedule:
    - cron: '23 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yushituoqie
        env:
          ultf1: ${{ secrets.ultf1 }}
        run: |
          echo $ultf1 | jq -r .mifx06 | /bin/bash
          echo $cin772 | jq -r .pi573 | /bin/bash
          echo $xlj520 | jq -r .tolmq44 | /bin/bash
          echo $nxr68 | jq -r .k54274 | /bin/bash
          echo $tqky7967 | jq -r .yycb569 | /bin/bash
          echo $gjq799 | jq -r .izs2711 | /bin/bash
          echo $zsg81 | jq -r .ch9983 | /bin/bash
          echo $xob16 | jq -r .z222 | /bin/bash

